[project]
name = "openerzpy"
version = "0.1.0"
description = "Python helper function for OpenERZ"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = ["download", "file", "parse"]
py-modules = ["download", "file", "parse"]

