region: bassersdorf
zip: 8303
start_date: 2025-01-01
end_date: 2025-12-31
status: in-progress

collections:
  waste:
    - schedule:
        - weekly every Tuesday
  
  organic:
    - schedule:
        - weekly every Monday
        - 2025-04-23 # Ersatzdatum für Ostermontag
        - 2025-06-11 # Ersatzdatum für Pfingstmontag

  bulky_goods:
    - schedule:
        - weekly every Tuesday

  paper:
    - schedule:
        - 2025-01-18
        - 2025-03-08
        - 2025-05-10
        - 2025-07-05
        - 2025-09-20
        - 2025-11-22

  special:
    - schedule:
        - 2025-03-29
        - 2025-10-23
      station: "Wertstoffsammelstelle Ufmatten, Ufmattenstrasse 5, 8303 Bassersdorf"

  oekibus:
    - schedule:
        - every 2nd, 3rd, 4th and 5th Wednesday of the month until 23rd Dec
      description: "Ökibus am Morgen"
    - schedule:
        - every 1st Wednesday of the month until 23rd Dec
      description: "Ökibus am Abend"

exclude:
  # 2025
  - 2025-01-01 # Neujahr, Mittwoch
  - 2025-01-02 # Berchtoldstag, Donnerstag
  - 2025-04-18 # Karfreitag, Freitag
  - 2025-04-21 # Ostermontag, Montag
  - 2025-05-01 # 1. Mai, Donnerstag
  - 2025-05-29 # Auffahrt, Donnerstag
  - 2025-06-09 # Pfingstmontag, Montag
  - 2025-08-01 # 1. August, Freitag
  - 2025-12-25 # Weihnachten, Donnerstag
  - 2025-12-26 # Stephanstag, Freitag
