region: gossau-zh
zip: 8625
start_date: 2026-01-01
end_date: 2026-12-31
status: done
cache:
  calendar: cache/gossau-zh.csv

collections:
  waste: ~
  bulky_goods: ~
  chipping_service: ~
  organic: ~
  paper: ~
  cardboard: ~
  special: ~