region: hombrechtikon
zip: 8634
start_date: 2026-01-01
end_date: 2026-12-31
status: done

collections:
  waste:
    - schedule:
        - weekly every Thursday
        - 2026-01-03 # Ersatzdatum für Neujahr, Donnerstag
        - 2026-05-16 # Ersatzdatum für Auffahrt

  bulky_goods:
    - schedule:
        - weekly every Thursday
        - 2026-01-03 # Ersatzdatum für Neujahr, Donnerstag
        - 2026-05-16 # Ersatzdatum für Auffahrt
  
  organic:
    - schedule:
        - every Wednesday
      exclude:
        - 2026-12-30 # keine Kartonsammlung an Silvester

  paper:
    - schedule:
        - 2025-03-07
        - 2025-06-27
        - 2025-11-14
  
  cardboard:
    - schedule:
        - 2025-01-07
        - 2025-03-11
        - 2025-05-06
        - 2025-07-08
        - 2025-09-16
        - 2025-11-11

  special:
    - schedule:
        - 2025-06-16
        - 2025-11-10
      station: "Sammelstelle Holflüe"

exclude:
  # 2026
  - 2026-01-01 # Neujahr, Donnerstag
  - 2026-01-02 # Berchtoldstag, Freitag
  - 2026-04-03 # Karfreitag, Freitag
  - 2026-04-06 # Ostermontag, Montag
  - 2026-05-01 # 1. Mai, Freitag
  - 2026-05-14 # Auffahrt, Donnerstag
  - 2026-05-25 # Pfingstmontag, Montag
  - 2026-08-01 # 1. August, Samstag
  - 2026-12-25 # Weihnachten, Freitag
  - 2026-12-26 # Stephanstag, Samstag
