region: horgen
start_date: 2025-01-01
end_date: 2025-12-31
status: in-progress

collections:
  cardboard: ~
  chipping_service: ~
  incombustibles: ~
  metal: ~
  organic: ~
  paper: ~
  special: ~
  waste: ~
