region: richterswil
start_date: 2026-01-01
end_date: 2026-12-31
status: done
cache:
  calendar: cache/richterswil.csv

collections:
  cardboard: ~
  chipping_service: ~
  organic: ~
  paper: ~
  special: ~
  waste: ~
