region: thalwil
start_date: 2026-01-01
end_date: 2026-12-31
status: done
cache:
  calendar: cache/thalwil.csv

collections:
  cardboard: ~
  incombustibles: ~
  metal: ~
  organic: ~
  paper: ~
  special: ~
  waste: ~
