region: wangen-bruttisellen
zip: 8306
start_date: 2026-01-01
end_date: 2026-12-31
status: done

collections:
  waste:
    - schedule:
        - weekly every Friday
        - 2026-04-01 # Ersatzdatum für Karfreitag
        - 2026-04-29 # Ersatzdatum für 1. Mai
        - 2026-12-23 # Ersatzdatum für Weihnachten
        - 2026-12-30 # Ersatzdatum für Neujahr 2027
  
  organic:
    - schedule:
        - every 2nd and 4th Monday in Jan
        - every 1st and 3rd Monday in Feb
        - weekly every Monday from March until December
        - every 1st and 3rd Monday in Dec
        - 2026-04-07 # Ersatzdatum für Ostermontag
        - 2026-06-26 # Ersatzdatum für Pfingsmontag

  chipping_service:
    - schedule:
        - 2026-03-24
        - 2026-03-25
        - 2026-03-26
        - 2026-10-27
        - 2026-10-28
        - 2026-10-29

  bulky_goods:
    - schedule:
        - weekly every Friday
        - 2026-04-01 # Ersatzdatum für Karfreitag
        - 2026-04-29 # Ersatzdatum für 1. Mai 

  paper:
    - schedule:
        - every first Saturday of the month
        - 2026-04-11 # Ersatzdatum für Karsamstag
        - 2026-08-08 # Ersatzdatum für 1. August
        - 2026-10-10 # Ersatzdatum Dorfchilbi Wangen

  cardboard:
    - schedule:
        - every first Wednesday of the month

  special:
    - schedule:
        - 2026-02-20 # Brüttisellen
      station: "Sonderabfallmobil, Werke Wangen-Brüttisellen, Zürichstrasse 22, 8306 Brüttisellen"
    - schedule:
        - 2026-09-30 # Wangen
      station: "Sonderabfallmobil, Schulhaus Oberwisen, Unterdorfstrasse 50, 8302 Wangen"

exclude:
  # 2026
  - 2026-01-01 # Neujahr, Donnerstag
  - 2026-01-02 # Berchtoldstag, Freitag
  - 2026-04-03 # Karfreitag, Freitag
  - 2026-04-06 # Ostermontag, Montag
  - 2026-05-01 # 1. Mai, Freitag
  - 2026-05-14 # Auffahrt, Donnerstag
  - 2026-05-25 # Pfingstmontag, Montag
  - 2026-08-01 # 1. August, Samstag
  - 2026-10-03 # Dorfchilbi Wangen
  - 2026-12-25 # Weihnachten, Freitag
  - 2026-12-26 # Stephanstag, Samstag
