region: wangen-bruttisellen
zip: 8306
start_date: 2025-01-01
end_date: 2025-12-31
status: in-progress

collections:
  waste:
    - schedule:
        - weekly every Friday
        - 2025-04-16 # Ersatzdatum für Karfreitag 
      exclude: ~
  
  organic:
    - schedule:
        - every 2nd and 4th Monday in Jan
        - every 1st and 3rd Monday in Feb
        - weekly every Monday from March until December
        - every 2nd and 4th Monday in Dec
        - 2025-04-23 # Ersatzdatum für Ostermontag
        - 2025-06-11 # Ersatzdatum für Pfingsmontag
      exclude: ~

  chipping_service:
    - schedule:
        - 2025-03-11
        - 2025-03-12
        - 2025-03-13
        - 2025-10-28
        - 2025-10-29
        - 2025-10-30
      exclude: ~

  bulky_goods:
    - schedule:
        - weekly every Friday
        - 2025-04-16 # Ersatzdatum für Karfreitag 
      exclude: ~

  paper:
    - schedule:
        - every first Saturday of the month
      exclude: ~

  cardboard:
    - schedule:
        - every first Wednesday of the month
        - 2024-01-08 # Ersatzdatum für Neujahr
      exclude: ~

  special:
    - schedule:
        - 2024-02-21 # Brüttisellen
      station: "Sonderabfallmobil, Zürichstrasse 22, 8306 Brüttisellen"
    - schedule:
        - 2024-09-13 # Wangen
      station: "Sonderabfallmobil, Schulhaus Oberwisen, Unterdorfstrasse 50, 8302 Wangen"

exclude:
  # 2025
  - 2025-01-01 # Neujahr, Mittwoch
  - 2025-01-02 # Berchtoldstag, Donnerstag
  - 2025-04-18 # Karfreitag, Freitag
  - 2025-04-21 # Ostermontag, Montag
  - 2025-05-01 # 1. Mai, Donnerstag
  - 2025-05-29 # Auffahrt, Donnerstag
  - 2025-06-09 # Pfingstmontag, Montag
  - 2025-08-01 # 1. August, Freitag
  - 2025-12-25 # Weihnachten, Donnerstag
  - 2025-12-26 # Stephanstag, Freitag
