region: wetzikon
start_date: 2026-01-01
end_date: 2026-12-31
zip: 8620
status: done
cache:
  calendar: cache/wetzikon.csv

collections:
  cardboard: ~
  chipping_service: ~
  incombustibles: ~
  metal: ~
  organic: ~
  paper: ~
  special: ~
  waste: ~
