region: wiesendangen
zip: 8542
start_date: 2026-01-01
end_date: 2026-12-31
status: done

collections:
  waste:
    - schedule:
        - weekly every Thursday
        - 2026-01-03 # Ersatzdatum für Neujahr
        - 2026-05-16 # Ersatzdatum für Auffahrt

  bulky_goods:
    - schedule:
        - weekly every Thursday
        - 2026-01-03 # Ersatzdatum für Neujahr
        - 2026-05-16 # Ersatzdatum für Auffahrt

  organic:
    - area: Dorf
      description: "Wiesendangen, Gundetswil, Bertschikon, Attikon"
      schedule:
        - weekly every Thursday
        - 2026-01-03 # Ersatzdatum für Neujahr
        - 2026-05-15 # Ersatzdatum für Auffahrt
    - area: Aussenwachten
      description: "Oberbertschikon, Bewangen, Buch, Gündlikon, Liebensberg, Menzengrüt, Meisberg, Sammelsgrüt, Stegen, Wallikon, Zünikon"
      schedule:
        - every other Thursday starting Jan 15
  
  chipping_service:
    - schedule:
        - 2026-03-23
        - 2026-04-27
        - 2026-09-14
        - 2026-10-19
      description: "Für den Häckselservice ist eine Anmeldung erforderlich"

  paper:
    - schedule:
        - 2026-03-09
        - 2026-06-08
        - 2026-09-07
        - 2026-12-07
      description: "Ganzjährig: Papier- und Kartoncontainer auf dem Trottenplatz Wiesendangen"
  
  cardboard:
    - area: Aussenwachten
      schedule:
        - 2026-03-09
        - 2026-06-08
        - 2026-09-07
        - 2026-12-07
      description: "Ganzjährig: Papier- und Kartoncontainer auf dem Trottenplatz Wiesendangen "

  special:
    - schedule:
        - 2026-04-07
        - 2026-12-01
      station: "Wiesendangen, Trottenplatz"
    - schedule:
        - 2026-12-01
      station: "Gundetswil, Werkhof"
    - schedule:
        - 2026-01-23
      station: "Rickenbach, Werkgebäude"
    - schedule:
        - 2026-03-14
      station: "Elsau, Werkgebäude"
    - schedule:
        - 2026-05-13
      station: "Hagenbuch, Werkhof"
    - schedule:
        - 2026-01-21
        - 2026-09-01
      station: "Seuzach, Werkhof"

exclude:
  # 2026
  - 2026-01-01 # Neujahr, Donnerstag
  - 2026-01-02 # Berchtoldstag, Freitag
  - 2026-04-03 # Karfreitag, Freitag
  - 2026-04-06 # Ostermontag, Montag
  - 2026-05-01 # 1. Mai, Freitag
  - 2026-05-14 # Auffahrt, Donnerstag
  - 2026-05-25 # Pfingstmontag, Montag
  - 2026-08-01 # 1. August, Samstag
  - 2026-12-25 # Weihnachten, Freitag
  - 2026-12-26 # Stephanstag, Samstag
