region: winterthur
start_date: 2026-01-01
end_date: 2026-12-31
zip: 8400
status: done
cache:
  calendar: cache/winterthur.csv

collections:
  cardboard: ~
  organic: ~
  paper: ~
  waste: ~
  metal: ~
