region: zurich
start_date: 2026-01-01
end_date: 2026-12-31
status: done
cache:
  station: cache/zurich_stationen.csv
  calendar: cache/zurich.csv

collections:
  cardboard: ~
  metal: ~
  mobile: ~
  organic: ~
  paper: ~
  special: ~
  textile: ~
  waste: ~
